import '../styles/globals.css';

import CarsLayout from '@/layouts/cars-layout';
import theme from '@/styles/theme-antd';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider } from 'antd';
import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';

const inter = Plus_Jakarta_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<AntdRegistry>
					<ConfigProvider prefixCls="ant" theme={{ ...theme }}>
						<CarsLayout>{children}</CarsLayout>
					</ConfigProvider>
				</AntdRegistry>
			</body>
		</html>
	);
}
